SQLALCHEMY_ECHO = False  # do not show SQL statements
SQLALCHEMY_TRACK_MODIFICATIONS = False  # suppress warnings
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:wizard@localhost:5432/wizard"
SECRET_KEY = "replace_this"
FIREBASE_CERT_NAME = "project-mobile-wizard-firebase-adminsdk-6bmre-c67afcaefa.json"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_DB = "0"
FRONTEND_URL = "http://localhost:4200"
